export const SOCKET_COMMANDS_EXECUTED = 'SOCKET_COMMANDS_EXECUTED';
export const CLIENT_CONNECTED = 'CLIENT_CONNECTED';
export const CLIENT_DISCONNECTED = 'CLIENT_DISCONNECTED';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const BROADCAST_SENT = 'BROADCAST_SENT';

