export const CLIENT_INIT = 'CLIENT_INIT';
export const NEW_CLIENT = 'NEW_CLIENT';
export const CLIENT_WENT_AWAY = 'CLIENT_WENT_AWAY';
export const NEW_MESSAGE = 'NEW_MESSAGE';
export const MESSAGE_HISTORY = 'MESSAGE_HISTORY';

