export const APP_LOADED = 'APP_LOADED';

export const SOCKET_CREATED = 'SOCKET_CREATED';
export const SOCKET_ERROR_OCCURRED = 'SOCKET_ERROR_OCCURRED';
export const SOCKET_LOCAL_STATE_UPDATED = 'SOCKET_LOCAL_STATE_UPDATED';
export const SOCKET_REMOTE_STATE_UPDATED = 'SOCKET_REMOTE_STATE_UPDATED';

